# Generated by Django 3.2.18 on 2023-05-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='m_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
