# Generated by Django 3.2.18 on 2023-05-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='providers',
            field=models.ManyToManyField(related_name='providers', to='movies.Provider'),
        ),
    ]
