# Generated by Django 3.2.18 on 2023-05-19 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='genre_id',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='provider_id',
        ),
    ]
