# Generated by Django 3.2.18 on 2023-05-22 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_providers'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='backdrop_path',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
