# Generated by Django 3.2.18 on 2023-05-17 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='user',
        ),
    ]
